### ISSUE TITLE
Proposal: Relicensing runtime-linked code to avoid copyright notice dependencies on binaries

### ISSUE THREAD

**Issue by asiekierka** [daid/gbsdk#17]
In short: It is often tough to comply with a copyright notice preservation requirement for binaries when self-contained ROMs are distributed digitally or on cartridge. Most projects do not comply with such requirements even today, leading to mass copyright infringement in homebrew scenes (for example, usage of newlib in GBA/NDS/PSP/Wii/3DS/... homebrew).

For this reason, many projects (my own WIP toolchain collection [Wonderful](https://github.com/WonderfulToolchain/wonderful-i8086), [libnds](https://github.com/devkitPro/libnds/blob/master/libnds_license.txt), smaller things like [decompressors](https://github.com/einar-saukas/ZX0/blob/main/z80/dzx0_fast.asm)) have opted to use, for the library code which is statically linked with the target binary, a license which does not impose such a requirement. Example options include:

 * the zlib license (my personal preference), which preserves the requirement for source code but not binary form,
 * the Boost Software License, which has a similar effect,
 * licenses which do not impose any attribution requirements, like CC0, 0-clause BSD, etc.

My suggestion is that, in order to allow building modern toolchains which are easy to comply with the license of by end users, the runtime library code (`inc/` and `src/` but not `tools/`), it would be worthwhile to consider relicensing said code in GBSDK to one of these licenses. GBSDK is in an unique position here, as it does not include decades of difficult-to-relicense legacy code.

**Comment by daid** [comment]
zlib license sounds good, that matches my intentions as well.

@QuinnPainter @forestbelton got an issue with a license change to zlib? (as you have contributions, I would need confirmation before I can change a license)

**Comment by QuinnPainter** [comment]
Sure, zlib sounds good to me.

**Comment by asiekierka** [comment]
As a note, @forestbelton 's contributions concern only the `rules.mk` file, so this would not impact relicensing the code itself.

**Comment by asiekierka** [comment]
Any updates on this? At least the runtime library code, which is what ends up being linked to the static binary.
